#LOCAL HOST =======================================
#RETRIEVE ALL ITEMS IN COLLECTION
GET http://localhost:3000/b-lists
###
#RETRIEVE ONE CONTACT FROM COLLECTION
GET http://localhost:3000/b-lists/6286c571862ae0680f18a76c
###
#CREATE NEW CONTACT 
POST http://localhost:3000/b-lists/ 
Content-Type: application/json 

{
    "name":"Sistine Chapel", "type":"history", "price":"1000", "city":"Vatican City", "month":"May", "year":"2030", "country":"Vatican"
}
###
#DELETE ONE CONTACT
DELETE http://localhost:3000/b-lists/6287f8c60c89bc76d3e6f4d4 HTTP/1.1
Content-Type: application/json
###
#UPDATE ONE CONTACT
PUT http://localhost:3000/b-lists/6286d697c07fa34ff8431556
Content-Type: application/json 

{
    "name":"Sistine Chapel", "type":"travel", "price":"21000", "city":"Vatican City", "month":"May", "year":"2030", "country":"Vatican"
}

###


#------------------------------HEROKU ENVIROMENT ---------------------------------------------------#
#GET ALL CONTACTS
GET https://cse341-prj2.herokuapp.com/b-lists
###
#GET ONE CONTACT 
GET https://cse341-prj2.herokuapp.com/b-lists/6286c571862ae0680f18a76c

### Create contact 
POST https://cse341-prj2.herokuapp.com/b-lists
Content-Type: application/json 

{
    "name":"Sistine Chapel", "type":"history", "price":"1000", "city":"Vatican City", "month":"May", "year":"2030", "country":"Vatican"
}

###DELETE contact 
DELETE https://cse341-prj2.herokuapp.com/b-lists/6286d50c881bf9ce9b90727f HTTP/1.1

###
#UPDATE ONE CONTACT
PUT https://cse341-prj2.herokuapp.com/b-lists/6286d50c881bf9ce9b90727f
Content-Type: application/json 

{
    "name":"Sistine Chapel", "type":"history", "price":"1000", "city":"Vatican City", "month":"May", "year":"2030", "country":"Vatican"
}
